/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smoothwheel;

import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.Desktop;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author User
 */
public class AboutUs extends javax.swing.JFrame {
    
    /**
     * Creates new form AboutUs
     */
    public AboutUs() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        // jScrollPane2.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        setIcon();
        //To make the text area1 trasnparent
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.setBorder(null);
        jScrollPane1.setViewportBorder(null);
        
        jTextArea1.setBorder(null);
        jTextArea1.setBackground(new Color(255, 234, 220, 0));
        jTextArea1.setEditable(false);
        
        //To make the text area2 trasnparent        
        jScrollPane2.setOpaque(false);
        jScrollPane2.getViewport().setOpaque(false);
        jScrollPane2.setBorder(null);
        jScrollPane2.setViewportBorder(null);
        
        jTextArea2.setBorder(null);
        jTextArea2.setBackground(new Color(255, 234, 220, 15));
        jTextArea2.setEditable(false);
        

    }
    
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Wheel.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLbl_IsraaEmail = new javax.swing.JLabel();
        jLbl_AreenEmail = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLbl_AreenEmail1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Smooth Wheel");

        jPanel1.setPreferredSize(new java.awt.Dimension(1088, 590));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Edwardian Script ITC", 1, 110)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Smooth Wheel  ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 580, 130);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setColumns(15);
        jTextArea1.setFont(new java.awt.Font("Vivaldi", 1, 25)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText(" Here is a world of ease and technology that we put in your hands, and we convert your congested and\n      scattered paper files into a fast system that is easy to manage and handle. Our motto is updating your\n         information with the click of a button.\n\n            Smooth Wheel is an app for a car rental system that makes the process of renting cars easier and\n                smoother for the owner that rents automobiles for short periods of time for a fee.");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(230, 130, 950, 220);

        jButton1.setBackground(new java.awt.Color(169, 166, 166));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 234, 220));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Return Back.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 550, 130, 80);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea2.setColumns(15);
        jTextArea2.setFont(new java.awt.Font("Vivaldi", 1, 25)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea2.setRows(5);
        jTextArea2.setText("We Would be happy to hear any\n   any comments from you, please don't\n     hesitate to contact us via our emails:");
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(880, 420, 370, 100);

        jLbl_IsraaEmail.setBackground(new java.awt.Color(237, 179, 141));
        jLbl_IsraaEmail.setFont(new java.awt.Font("Vivaldi", 1, 25)); // NOI18N
        jLbl_IsraaEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLbl_IsraaEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbl_IsraaEmail.setText(" israa.k.odeh@gmail.com");
        jLbl_IsraaEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLbl_IsraaEmail.setOpaque(true);
        jLbl_IsraaEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbl_IsraaEmailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbl_IsraaEmailMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLbl_IsraaEmailMousePressed(evt);
            }
        });
        jPanel1.add(jLbl_IsraaEmail);
        jLbl_IsraaEmail.setBounds(950, 530, 250, 30);

        jLbl_AreenEmail.setBackground(new java.awt.Color(237, 179, 141));
        jLbl_AreenEmail.setFont(new java.awt.Font("Vivaldi", 1, 25)); // NOI18N
        jLbl_AreenEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLbl_AreenEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbl_AreenEmail.setText(" areenateeq2019@yahoo.com");
        jLbl_AreenEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLbl_AreenEmail.setOpaque(true);
        jLbl_AreenEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbl_AreenEmailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbl_AreenEmailMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLbl_AreenEmailMousePressed(evt);
            }
        });
        jPanel1.add(jLbl_AreenEmail);
        jLbl_AreenEmail.setBounds(950, 570, 250, 30);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/About Us.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1330, 660);

        jLbl_AreenEmail1.setBackground(new java.awt.Color(4, 39, 74));
        jLbl_AreenEmail1.setFont(new java.awt.Font("Vivaldi", 1, 25)); // NOI18N
        jLbl_AreenEmail1.setForeground(new java.awt.Color(255, 255, 255));
        jLbl_AreenEmail1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbl_AreenEmail1.setText(" areenateeq2019@yahoo.com");
        jLbl_AreenEmail1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLbl_AreenEmail1.setOpaque(true);
        jLbl_AreenEmail1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbl_AreenEmail1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbl_AreenEmail1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLbl_AreenEmail1MousePressed(evt);
            }
        });
        jPanel1.add(jLbl_AreenEmail1);
        jLbl_AreenEmail1.setBounds(950, 570, 250, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1330, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new MainInterface().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLbl_IsraaEmailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_IsraaEmailMousePressed
        try {
            Desktop.getDesktop().mail(new URI("mailto:israa.k.odeh@gmail.com"));
            //Desktop.getDesktop().mail(new URI("mailto:israa.k.odeh@gmail.com?subject=TEST"));
        }
        catch (URISyntaxException | IOException ex) {
            //Logger.getLogger(AboutUs.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLbl_IsraaEmailMousePressed

    private void jLbl_IsraaEmailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_IsraaEmailMouseEntered
        jLbl_IsraaEmail.setForeground(Color.blue);
        //To make the emails underlined
        String email1 = "<html>  <u> israa.k.odeh@gmail.com </u>" ;
        //String email1 = "<html> &nbsp <u> israa.k.odeh@gmail.com </u>" ; to add space
        jLbl_IsraaEmail.setText(email1);
    }//GEN-LAST:event_jLbl_IsraaEmailMouseEntered

    private void jLbl_IsraaEmailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_IsraaEmailMouseExited
        jLbl_IsraaEmail.setForeground(Color.white);
        jLbl_IsraaEmail.setText("israa.k.odeh@gmail.com");
    }//GEN-LAST:event_jLbl_IsraaEmailMouseExited

    private void jLbl_AreenEmailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_AreenEmailMousePressed
        try {
            Desktop.getDesktop().mail(new URI("mailto:areenateeq2019@yahoo.com"));
        }
        catch (URISyntaxException | IOException ex) {
            //Logger.getLogger(AboutUs.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLbl_AreenEmailMousePressed

    private void jLbl_AreenEmailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_AreenEmailMouseEntered
        jLbl_AreenEmail.setForeground(Color.blue);
        String email2 = "<html> <u> areenateeq2019@yahoo.com </u>" ;
        jLbl_AreenEmail.setText(email2);
    }//GEN-LAST:event_jLbl_AreenEmailMouseEntered

    private void jLbl_AreenEmailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_AreenEmailMouseExited
        jLbl_AreenEmail.setForeground(Color.white);
                jLbl_AreenEmail.setText("areenateeq2019@yahoo.com");
    }//GEN-LAST:event_jLbl_AreenEmailMouseExited

    private void jLbl_AreenEmail1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_AreenEmail1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbl_AreenEmail1MouseEntered

    private void jLbl_AreenEmail1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_AreenEmail1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbl_AreenEmail1MouseExited

    private void jLbl_AreenEmail1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_AreenEmail1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbl_AreenEmail1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutUs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLbl_AreenEmail;
    private javax.swing.JLabel jLbl_AreenEmail1;
    private javax.swing.JLabel jLbl_IsraaEmail;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
