/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smoothwheel;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.*;
import oracle.jdbc.*;
import oracle.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class CarsTable extends javax.swing.JFrame {

    private int selectedRowIndex;

    /**
     * Creates new form CarsTable
     */
    public CarsTable() {
        initComponents();
        jTbl_Car.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 15));
        jTbl_Car.getTableHeader().setOpaque(false);
        jTbl_Car.setRowHeight(25);
        jScrollPane1.getViewport().setBackground(new Color(237,228,213));
    }

    public JTable getTableName() {
        return jTbl_Car;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbl_Car = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(237, 228, 213));
        jLabel1.setFont(new java.awt.Font("Edwardian Script ITC", 1, 40)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N
        jLabel1.setText("Smooth Wheel  ");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 56));

        jTbl_Car.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Car ID", "Manufacturer Company", "Model", "Color", "Engine Power", "Gear Type", "Fuel Type", "Fuel Tank Capacity", "Seat Capacity", "Rental Fee Per Day"
            }
        ));
        jTbl_Car.setGridColor(new java.awt.Color(153, 0, 51));
        jTbl_Car.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTbl_Car.setRowHeight(25);
        jTbl_Car.setSelectionBackground(new java.awt.Color(72, 87, 128));
        jTbl_Car.setShowGrid(true);
        jTbl_Car.setShowHorizontalLines(false);
        jTbl_Car.getTableHeader().setReorderingAllowed(false);
        jTbl_Car.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbl_CarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTbl_Car);
        if (jTbl_Car.getColumnModel().getColumnCount() > 0) {
            jTbl_Car.getColumnModel().getColumn(0).setMinWidth(80);
            jTbl_Car.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTbl_Car.getColumnModel().getColumn(0).setMaxWidth(80);
            jTbl_Car.getColumnModel().getColumn(1).setMinWidth(200);
            jTbl_Car.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTbl_Car.getColumnModel().getColumn(1).setMaxWidth(200);
            jTbl_Car.getColumnModel().getColumn(2).setMinWidth(150);
            jTbl_Car.getColumnModel().getColumn(2).setPreferredWidth(150);
            jTbl_Car.getColumnModel().getColumn(2).setMaxWidth(150);
            jTbl_Car.getColumnModel().getColumn(3).setMinWidth(80);
            jTbl_Car.getColumnModel().getColumn(3).setPreferredWidth(80);
            jTbl_Car.getColumnModel().getColumn(3).setMaxWidth(80);
            jTbl_Car.getColumnModel().getColumn(4).setMinWidth(130);
            jTbl_Car.getColumnModel().getColumn(4).setPreferredWidth(130);
            jTbl_Car.getColumnModel().getColumn(4).setMaxWidth(130);
            jTbl_Car.getColumnModel().getColumn(5).setMinWidth(100);
            jTbl_Car.getColumnModel().getColumn(5).setPreferredWidth(100);
            jTbl_Car.getColumnModel().getColumn(5).setMaxWidth(100);
            jTbl_Car.getColumnModel().getColumn(6).setMinWidth(100);
            jTbl_Car.getColumnModel().getColumn(6).setPreferredWidth(100);
            jTbl_Car.getColumnModel().getColumn(6).setMaxWidth(100);
            jTbl_Car.getColumnModel().getColumn(8).setMinWidth(110);
            jTbl_Car.getColumnModel().getColumn(8).setPreferredWidth(110);
            jTbl_Car.getColumnModel().getColumn(8).setMaxWidth(110);
            jTbl_Car.getColumnModel().getColumn(9).setMinWidth(150);
            jTbl_Car.getColumnModel().getColumn(9).setPreferredWidth(150);
            jTbl_Car.getColumnModel().getColumn(9).setMaxWidth(150);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 52, 1280, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTbl_CarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbl_CarMouseClicked
        DefaultTableModel carsTableModel = (DefaultTableModel) jTbl_Car.getModel();
        selectedRowIndex = jTbl_Car.getSelectedRow();
        CarRegistration currentCarInterface = new CarRegistration();
        currentCarInterface = currentCarInterface.getCurrentInterface();
        currentCarInterface.setVisible(true);
        currentCarInterface.setCarID(carsTableModel.getValueAt(selectedRowIndex, 0).toString());
        currentCarInterface.setManufacturerCompany(carsTableModel.getValueAt(selectedRowIndex, 1).toString());
        currentCarInterface.setModel(carsTableModel.getValueAt(selectedRowIndex, 2).toString());
        currentCarInterface.setColor(carsTableModel.getValueAt(selectedRowIndex, 3).toString());
        currentCarInterface.setEnginePower(carsTableModel.getValueAt(selectedRowIndex, 4).toString());
        currentCarInterface.setGearType(carsTableModel.getValueAt(selectedRowIndex, 5).toString());
        currentCarInterface.setFuelType(carsTableModel.getValueAt(selectedRowIndex, 6).toString());
        currentCarInterface.setTankCapacity(carsTableModel.getValueAt(selectedRowIndex, 7).toString());
        currentCarInterface.setSeatCapacity(carsTableModel.getValueAt(selectedRowIndex, 8).toString());
        currentCarInterface.setRentalFeePerDay(carsTableModel.getValueAt(selectedRowIndex, 9).toString());
    }//GEN-LAST:event_jTbl_CarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarsTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarsTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarsTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarsTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarsTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTbl_Car;
    // End of variables declaration//GEN-END:variables

}
