/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smoothwheel;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class MaintenanceTable extends javax.swing.JFrame {

    private int selectedRowIndex;

    /**
     * Creates new form CarsTable
     */
    public MaintenanceTable() {
        initComponents();
        jTbl_Maintenance.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 15));
        jTbl_Maintenance.getTableHeader().setOpaque(false);
        jTbl_Maintenance.setRowHeight(25);
        jScrollPane1.getViewport().setBackground(new Color(237,228,213));
    }

    public JTable getTableName() {
        return jTbl_Maintenance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLbl_Heading = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbl_Maintenance = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLbl_Heading.setBackground(new java.awt.Color(237, 228, 213));
        jLbl_Heading.setFont(new java.awt.Font("Edwardian Script ITC", 1, 40)); // NOI18N
        jLbl_Heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbl_Heading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N
        jLbl_Heading.setText("Smooth Wheel  ");
        jLbl_Heading.setOpaque(true);
        jPanel1.add(jLbl_Heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 56));

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setOpaque(false);

        jTbl_Maintenance.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTbl_Maintenance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Maintenance ID", "Car ID"
            }
        ));
        jTbl_Maintenance.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTbl_Maintenance.setRowHeight(25);
        jTbl_Maintenance.setSelectionBackground(new java.awt.Color(72, 87, 128));
        jTbl_Maintenance.setShowGrid(true);
        jTbl_Maintenance.setShowHorizontalLines(false);
        jTbl_Maintenance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbl_MaintenanceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTbl_Maintenance);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 52, 1280, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTbl_MaintenanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbl_MaintenanceMouseClicked
        DefaultTableModel maintenanceTableModel = (DefaultTableModel) jTbl_Maintenance.getModel();
        selectedRowIndex = jTbl_Maintenance.getSelectedRow();
        Maintenance currentMaintenanceInterface = new Maintenance();
        currentMaintenanceInterface = currentMaintenanceInterface.getCurrentInterface();
        currentMaintenanceInterface.setVisible(true);
        currentMaintenanceInterface.setMaintenanceID(maintenanceTableModel.getValueAt(selectedRowIndex, 0).toString());
        currentMaintenanceInterface.setCarID(maintenanceTableModel.getValueAt(selectedRowIndex, 1).toString());
    }//GEN-LAST:event_jTbl_MaintenanceMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MaintenanceTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MaintenanceTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MaintenanceTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MaintenanceTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MaintenanceTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLbl_Heading;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTbl_Maintenance;
    // End of variables declaration//GEN-END:variables
}
