/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smoothwheel;

import javax.swing.JFrame;
import java.awt.Color;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author ALFALAK
 */
public class SignIN extends javax.swing.JFrame {

    /**
     * Creates new form firstone
     */
    public SignIN() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.icon2.setVisible(false);
    }

    private void callTimer(JFrame notification) {
        Timer timer = new Timer();
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                notification.setVisible(false);
            }
        }, 6000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        icon2 = new javax.swing.JLabel();
        icon1 = new javax.swing.JLabel();
        jTxt_Password = new javax.swing.JPasswordField();
        jTxt_UserName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ReturnBack = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Smooth Wheel");
        setPreferredSize(new java.awt.Dimension(1430, 800));
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/passwordIcon.png"))); // NOI18N
        jLabel3.setText(" passWord   :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(550, 390, 270, 60);

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/UserNameIcon.png"))); // NOI18N
        jLabel4.setText("user name   :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(550, 280, 260, 70);

        icon2.setBackground(new Color (0,0,0,34));
        icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Visible.png"))); // NOI18N
        icon2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                icon2MousePressed(evt);
            }
        });
        getContentPane().add(icon2);
        icon2.setBounds(1040, 380, 50, 40);

        icon1.setBackground(new Color (0,0,0,34));
        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/InVisible.png"))); // NOI18N
        icon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                icon1MousePressed(evt);
            }
        });
        getContentPane().add(icon1);
        icon1.setBounds(1040, 380, 50, 40);

        jTxt_Password.setBackground(new Color (255,255,255,0));
        jTxt_Password.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTxt_Password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jTxt_Password.setOpaque(false);
        getContentPane().add(jTxt_Password);
        jTxt_Password.setBounds(810, 380, 270, 40);

        jTxt_UserName.setBackground(new Color(255,255,255,0));
        jTxt_UserName.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jTxt_UserName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jTxt_UserName.setOpaque(false);
        getContentPane().add(jTxt_UserName);
        jTxt_UserName.setBounds(810, 280, 270, 50);

        jLabel6.setBackground(new Color (204,204,255,90));
        jLabel6.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("LOG IN FORM");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(550, 200, 540, 70);

        jLabel7.setBackground(new Color (0,0,0,30));
        jLabel7.setFont(new java.awt.Font("Edwardian Script ITC", 1, 110)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Smooth Wheel     ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 20, 710, 110);

        ReturnBack.setBackground(new java.awt.Color(255, 204, 204));
        ReturnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Return Back.png"))); // NOI18N
        ReturnBack.setFocusPainted(false);
        ReturnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnBackActionPerformed(evt);
            }
        });
        getContentPane().add(ReturnBack);
        ReturnBack.setBounds(10, 550, 130, 80);

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jButton1.setText("LOG IN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(810, 500, 280, 70);

        jLabel5.setBackground(new Color (0,0,0,30));
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(550, 200, 540, 370);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LogIn.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-130, -340, 2150, 1030);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void icon1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon1MousePressed
        // TODO add your handling code here:
        icon2.setVisible(true);
        icon1.setVisible(false);
        jTxt_Password.setEchoChar((char) 0);
    }//GEN-LAST:event_icon1MousePressed

    private void icon2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon2MousePressed
        // TODO add your handling code here:
        icon1.setVisible(true);
        icon2.setVisible(false);
        jTxt_Password.setEchoChar('*');


    }//GEN-LAST:event_icon2MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String password = new String(jTxt_Password.getPassword());
        if (jTxt_UserName.getText().equals("") || jTxt_Password.equals("")) {
            ErrorNotification error = new ErrorNotification();
            error.setText("Please enter your name and your Password!");
            error.setVisible(true);
            callTimer(error);
        } else if (jTxt_UserName.getText().equals("Israa Odeh") && password.equals("IsraaOdeh5")) {
            LoadingInterface splashScreen = new LoadingInterface();
            this.setVisible(false);
            splashScreen.setVisible(true);
            Timer timer = new Timer();
            timer.schedule(new TimerTask() {
            @Override
            public void run() {
                WelcomeInterface welcomeInterface = new WelcomeInterface();
                splashScreen.setVisible(false);
                welcomeInterface.setVisible(true);
            }
        }, 10500);
        }
        else if (!jTxt_UserName.getText().equals("Israa Odeh") && !password.equals("IsraaOdeh5")) {
            ErrorNotification error = new ErrorNotification();
            error.setText("Incorrect Username and Password!");
            error.setVisible(true);
            callTimer(error);
        } 
        else if (!jTxt_UserName.getText().equals("Israa Odeh")) {
            ErrorNotification error = new ErrorNotification();
            error.setText("Incorrect Username!");
            error.setVisible(true);
            callTimer(error);
        } 
        else if (!password.equals("IsraaOdeh5")) {
            ErrorNotification error = new ErrorNotification();
            error.setText("Incorrect Password!");
            error.setVisible(true);
            callTimer(error);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ReturnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnBackActionPerformed
        new MainInterface().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ReturnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ReturnBack;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jTxt_Password;
    private javax.swing.JTextField jTxt_UserName;
    // End of variables declaration//GEN-END:variables
}
