/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smoothwheel;

import java.awt.Color;
import java.awt.ComponentOrientation;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
//import net.sf.jasperreports.engine.JRException;
//import net.sf.jasperreports.engine.JasperCompileManager;
//import net.sf.jasperreports.engine.JasperExportManager;
//import net.sf.jasperreports.engine.JasperFillManager;
//import net.sf.jasperreports.engine.JasperPrint;
//import net.sf.jasperreports.engine.JasperReport;
//import net.sf.jasperreports.engine.design.JRDesignQuery;
//import net.sf.jasperreports.engine.design.JasperDesign;
//import net.sf.jasperreports.engine.xml.JRXmlLoader;
//import net.sf.jasperreports.view.JasperViewer;
import oracle.jdbc.pool.OracleDataSource;

/**
 *
 * @author User
 */
public class WelcomeInterface extends javax.swing.JFrame {

    /**
     * Creates new form WelcomeInterface1
     */
    public WelcomeInterface() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        jScrollPane1.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);

        jScrollPane2.setOpaque(false);
        jScrollPane2.getViewport().setOpaque(false);
        jScrollPane2.setBorder(null);
        jScrollPane2.setViewportBorder(null);

        jTextArea1.setBorder(null);
        jTextArea1.setBackground(new Color(255, 255, 255, 30));
        jTextArea1.setEditable(false);
    }

    private void callTimer(JFrame notification) {
        Timer timer = new Timer();
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                notification.setVisible(false);
            }
        }, 6000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jBtn_CarReg = new javax.swing.JButton();
        jBtn_CustomersList = new javax.swing.JButton();
        jBtn_Rent = new javax.swing.JButton();
        jBtn_Return = new javax.swing.JButton();
        jBtn_EmployeesReg = new javax.swing.JButton();
        jBtn_Maintenance = new javax.swing.JButton();
        jBtn_Report = new javax.swing.JButton();
        jBtn_LogOut = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(91, 86, 86));
        jPanel1.setLayout(null);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0, 50));

        jBtn_CarReg.setBackground(new java.awt.Color(226, 228, 232));
        jBtn_CarReg.setFont(new java.awt.Font("Javanese Text", 1, 25)); // NOI18N
        jBtn_CarReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Car Registration.png"))); // NOI18N
        jBtn_CarReg.setText(" Car Registration ");
        jBtn_CarReg.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jBtn_CarReg.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBtn_CarReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_CarRegActionPerformed(evt);
            }
        });

        jBtn_CustomersList.setBackground(new java.awt.Color(21, 20, 20));
        jBtn_CustomersList.setFont(new java.awt.Font("Javanese Text", 1, 25)); // NOI18N
        jBtn_CustomersList.setForeground(new java.awt.Color(255, 255, 255));
        jBtn_CustomersList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Customers.png"))); // NOI18N
        jBtn_CustomersList.setText(" Customers Registration");
        jBtn_CustomersList.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBtn_CustomersList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_CustomersListActionPerformed(evt);
            }
        });

        jBtn_Rent.setBackground(new java.awt.Color(21, 20, 20));
        jBtn_Rent.setFont(new java.awt.Font("Javanese Text", 1, 25)); // NOI18N
        jBtn_Rent.setForeground(new java.awt.Color(255, 255, 255));
        jBtn_Rent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Rent.png"))); // NOI18N
        jBtn_Rent.setText(" Rent A Car ");
        jBtn_Rent.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBtn_Rent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_RentActionPerformed(evt);
            }
        });

        jBtn_Return.setBackground(new java.awt.Color(226, 228, 232));
        jBtn_Return.setFont(new java.awt.Font("Javanese Text", 1, 25)); // NOI18N
        jBtn_Return.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Return.png"))); // NOI18N
        jBtn_Return.setText(" Return A Car ");
        jBtn_Return.setHideActionText(true);
        jBtn_Return.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBtn_Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ReturnActionPerformed(evt);
            }
        });

        jBtn_EmployeesReg.setBackground(new java.awt.Color(226, 228, 232));
        jBtn_EmployeesReg.setFont(new java.awt.Font("Javanese Text", 1, 23)); // NOI18N
        jBtn_EmployeesReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Employee.png"))); // NOI18N
        jBtn_EmployeesReg.setText(" Employee Registration");
        jBtn_EmployeesReg.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBtn_EmployeesReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_EmployeesRegActionPerformed(evt);
            }
        });

        jBtn_Maintenance.setBackground(new java.awt.Color(21, 20, 20));
        jBtn_Maintenance.setFont(new java.awt.Font("Javanese Text", 1, 25)); // NOI18N
        jBtn_Maintenance.setForeground(new java.awt.Color(255, 255, 255));
        jBtn_Maintenance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Maintenance.png"))); // NOI18N
        jBtn_Maintenance.setText(" Maintenance");
        jBtn_Maintenance.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBtn_Maintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_MaintenanceActionPerformed(evt);
            }
        });

        jBtn_Report.setBackground(new java.awt.Color(226, 228, 232));
        jBtn_Report.setFont(new java.awt.Font("Javanese Text", 1, 25)); // NOI18N
        jBtn_Report.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Report.png"))); // NOI18N
        jBtn_Report.setText(" Reports");
        jBtn_Report.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBtn_Report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ReportActionPerformed(evt);
            }
        });

        jBtn_LogOut.setBackground(new java.awt.Color(21, 20, 20));
        jBtn_LogOut.setFont(new java.awt.Font("Javanese Text", 1, 25)); // NOI18N
        jBtn_LogOut.setForeground(new java.awt.Color(255, 255, 255));
        jBtn_LogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Log Out.png"))); // NOI18N
        jBtn_LogOut.setText(" Log Out");
        jBtn_LogOut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBtn_LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_LogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 211, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jBtn_EmployeesReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtn_Rent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtn_Return, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtn_Maintenance, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtn_Report, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtn_LogOut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtn_CarReg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtn_CustomersList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtn_CarReg, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtn_CustomersList, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtn_EmployeesReg, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtn_Rent, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtn_Return, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtn_Maintenance, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtn_Report, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtn_LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(249, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 400, 760);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(15);
        jTextArea1.setFont(new java.awt.Font("Vivaldi", 1, 25)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("                               \n                                     Welcome to Smooth Wheel!\n\n            We promise you that you’ll never struggle with the car renting process anymore\n                  by choosing Smooth Wheel,  you've taken your first step towards  a happier, \n                       practical  life as an owner of a car rental  company.\n\n                         We'll do everything we can to help and support you in your rental company.");
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(400, 0, 880, 260);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/WelcomeInterface1.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 0, 1250, 830);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/WelcomeInterface2.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 40, 830);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1282, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_CarRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_CarRegActionPerformed
        new CarRegistration().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtn_CarRegActionPerformed

    private void jBtn_RentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_RentActionPerformed
        new Rental().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtn_RentActionPerformed

    private void jBtn_ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ReturnActionPerformed
        new Return().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtn_ReturnActionPerformed

    private void jBtn_CustomersListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_CustomersListActionPerformed
        new CustomerRegistration().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtn_CustomersListActionPerformed

    private void jBtn_EmployeesRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_EmployeesRegActionPerformed
        new Employee().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtn_EmployeesRegActionPerformed

    private void jBtn_MaintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_MaintenanceActionPerformed
        new Maintenance().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtn_MaintenanceActionPerformed

    private void jBtn_ReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ReportActionPerformed

        try {
            OracleDataSource dataSource = new OracleDataSource();
            dataSource.setURL("jdbc:oracle:thin:C##IsraaOdeh/IsraaOdeh5@localhost:1521:xe");
            dataSource.setUser("c##IsraaOdeh");
            dataSource.setPassword("IsraaOdeh5");
            Connection connection = dataSource.getConnection();
            InputStream input = new FileInputStream(new File("CarsReport.jrxml"));
            JasperDesign carReportDesign = JRXmlLoader.load(input);
            JasperReport carReport = JasperCompileManager.compileReport(carReportDesign);
            JasperPrint printer = JasperFillManager.fillReport(carReport, null, connection);
            OutputStream output = new FileOutputStream(new File("CarsReport.pdf"));
            JasperExportManager.exportReportToPdfStream(printer, output);

            //JasperViewer.viewReport(printer);
            output.close();
            input.close();

            InputStream customerInput = new FileInputStream(new File("CustomersReport.jrxml"));
            JasperDesign customerReportDesign = JRXmlLoader.load(customerInput);
            JasperReport customerReport = JasperCompileManager.compileReport(customerReportDesign);
            JasperPrint customerPrinter = JasperFillManager.fillReport(customerReport, null, connection);
            OutputStream customerOutput = new FileOutputStream(new File("CustomersReport.pdf"));
            JasperExportManager.exportReportToPdfStream(customerPrinter, customerOutput);
            JasperViewer.viewReport(customerPrinter);

            SuccessNotification success = new SuccessNotification();
            success.setVisible(true);
            success.setText("<html> The Reports are successfully generated.</html>");
            callTimer(success);

            customerOutput.close();
            customerInput.close();
            connection.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "The File doesn't exist!");
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_jBtn_ReportActionPerformed

    private void jBtn_LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_LogOutActionPerformed
        new SignIN().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtn_LogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_CarReg;
    private javax.swing.JButton jBtn_CustomersList;
    private javax.swing.JButton jBtn_EmployeesReg;
    private javax.swing.JButton jBtn_LogOut;
    private javax.swing.JButton jBtn_Maintenance;
    private javax.swing.JButton jBtn_Rent;
    private javax.swing.JButton jBtn_Report;
    private javax.swing.JButton jBtn_Return;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
